### ISSUE TITLE
Understanding user stories 

### ISSUE THREAD

**Issue by Saarthak09** [assiontetteh/smarter-university-system#55]
Activity for Epic #52:
Understanding user stories for requirement prioritization

**Comment by Saarthak09** [comment]
There are some user stories which are not clear to me @assiontetteh can you please help me with this?

**Comment by agvidit1** [comment]
@Saarthak09 Sure, lets go through some user stories to ensure all are on the same page.

**Comment by agvidit1** [comment]
@Saarthak09 I believe we have established clear understanding of various user stories and the differences.

**Comment by Saarthak09** [comment]
@agvidit1 thanks for the review.
