### ISSUE TITLE
Implementing binary tree algorithm, to decide the priority - by Vidit

### ISSUE THREAD

**Issue by Saarthak09** [assiontetteh/smarter-university-system#56]
Activity for Epic #52:
Each member decides the user story priority by using the binary tree algorithm. 
Hence this task is assigned to Vidit to create his binary tree and decide priority using the tree.

**Comment by agvidit1** [comment]
I have completed my binary tree alogrithm, request folks to verify that priorities match with the tree created.

**Comment by SuDhAnShU-0611** [comment]
Verified the priorities, they match with the tree created
