### ISSUE TITLE
Combining the priorities of team members into an overall priority for each requirement

### ISSUE THREAD

**Issue by Saarthak09** [assiontetteh/smarter-university-system#58]
Activity for Epic #52:
Deciding the overall priority of the requirements by combining the priorities decided by all the team members

**Comment by assiontetteh** [comment]
@agvidit1 each Team member has completed their respective priority list for the User Stories. We will need to review them together during our next meeting.

**Comment by agvidit1** [comment]
@assiontetteh Sure, I believe we would need to do that in our next meeting. @Saarthak09 to ensure we can properly combine all the priorities in overall priority.

**Comment by SuDhAnShU-0611** [comment]
@assiontetteh  I have completed my respective priority list for user stories, please can you review it and ensure that its correct?

**Comment by Saarthak09** [comment]
> @assiontetteh Sure, I believe we would need to do that in our next meeting. @Saarthak09 to ensure we can properly combine all the priorities in overall priority.

Done as suggested.
