### ISSUE TITLE
Creating binary trees in GraphViz - Vidit

### ISSUE THREAD

**Issue by Saarthak09** [assiontetteh/smarter-university-system#60]
Activity for Epic #52:
Visualizing the requirement prioritized using binary tree algorithm by using GraphViz
This Issue is created for Vidit to complete and document his digraph.

**Comment by agvidit1** [comment]
Code for the binary tree has been completed and the code along with diagram has been added in the following doc: https://docs.google.com/document/d/1BMCESI7vp-z1goPRvHmq-gmGbdhuhDwSP3Io0zQ7_HQ/edit
