### ISSUE TITLE
Identify the type of users(actors), the goal, and the motivation for user stories.

### ISSUE THREAD

**Issue by Shanks0407** [assiontetteh/smarter-university-system#61]
Activity for #50 
Task to identify nouns as actors, the goal that each actor is trying to achieve, and the motivation behind each goal.

**Comment by Shanks0407** [comment]
Hi @assiontetteh can you please identify the actor, goal and motivation for each goals you identified and list them for the user stories.

**Comment by agvidit1** [comment]
@assiontetteh Thanks for documenting each actor and their motivation in the excel.
