### ISSUE TITLE
Making spreadsheet for user stories and capture the requirements rank

### ISSUE THREAD

**Issue by Saarthak09** [assiontetteh/smarter-university-system#62]
Activity for Epic #52:
Making spreadsheet with the user stories and adding columns to capture the requirements rank for each of the team members as well as the total overall requirements rank

**Comment by Saarthak09** [comment]
I have added the user stories assigned to me. @agvidit1 can you review it?

**Comment by Shanks0407** [comment]
I have created the user stories assigned to me. @assiontetteh can you please check to make sure they align with the actors identified by you.

**Comment by SuDhAnShU-0611** [comment]
I have created the user stories assigned to me.

**Comment by agvidit1** [comment]
@Saarthak09 Yes I have reviewed it, the excel looks good. Also @Shanks0407 they align with actors identified earlier.
