### ISSUE TITLE
Create Issues for Epics under MVP Software Requirements

### ISSUE THREAD

**Issue by agvidit1** [assiontetteh/smarter-university-system#67]
Activity for Epic #49 

Add Creating Issues and assign epic label for all epics under MVP- Software Requirements

**Comment by Saarthak09** [comment]
@agvidit1 thanks for creating the issues for epics.

**Comment by agvidit1** [comment]
@Saarthak09 No problem. Also thanks @assiontetteh For creating issues for the epic MVP software engineering.
