### ISSUE TITLE
Each User story must be assigned a unique identifier.

### ISSUE THREAD

**Issue by Shanks0407** [assiontetteh/smarter-university-system#68]
Activity for #50 
Task to assign a unique identifier to each user story so that they can be identified separately.

**Comment by SuDhAnShU-0611** [comment]
@agvidit1 Can you help me just in final reviewing whether unique identifier is assigned to each user story?

**Comment by agvidit1** [comment]
@SuDhAnShU-0611 Yes, it looks good. Every user story has been assigned unique identifier in the excel.
