### ISSUE TITLE
Document all the user stories to the spreadsheet.

### ISSUE THREAD

**Issue by Shanks0407** [assiontetteh/smarter-university-system#70]
Activity for #50 
Task to document all the user stories in the spreadsheet so that they are ready to be delivered.

**Comment by Saarthak09** [comment]
@agvidit1 @assiontetteh @SuDhAnShU-0611 @Shanks0407 I have added all the user stories to the spredsheet document. Kindly review.

**Comment by Shanks0407** [comment]
@Saarthak09 they look good to me. Great Work

**Comment by assiontetteh** [comment]
@Saarthak09 I have gone through it. It looks good.

**Comment by SuDhAnShU-0611** [comment]
@Saarthak09 Great work! Looks good.

**Comment by Saarthak09** [comment]
Thanks for the review everyone.
