### ISSUE TITLE
Add all the activities in TODO the scrum board

### ISSUE THREAD

**Issue by assiontetteh** [assiontetteh/smarter-university-system#73]
Activity for #54 
Add only activities but no MVPs or Epics

**Comment by agvidit1** [comment]
@Shanks0407  Can you help me identify the activities which have been created by you regarding individual graphiz binary tree creation which needs to be added.

**Comment by Shanks0407** [comment]
sure @agvidit1 the activities for  individual graphiz binary tree creation that needs to be added are #60 #94  #95 #96  and #97

**Comment by agvidit1** [comment]
@Shanks0407 Thanks for the update, all the activities were moved to the to-do section.
