### ISSUE TITLE
Periodically move activities from To Do to In Progress state

### ISSUE THREAD

**Issue by assiontetteh** [assiontetteh/smarter-university-system#75]
Activity for #54 
Update each activity status to show the current status.

**Comment by Saarthak09** [comment]
@Shanks0407 can you please update the progress of all the tasks we have completed so far?

**Comment by Shanks0407** [comment]
Sure @Saarthak09 , I will be moving the tasked that were completed by today to the done section and send a list of them over to you via email. Also I will add new task that we need to do to the todo list tomorrow morning.

**Comment by Shanks0407** [comment]
I have moved all the completed tasks to the done section.
