### ISSUE TITLE
Ensuring issues completed are closed in time

### ISSUE THREAD

**Issue by assiontetteh** [assiontetteh/smarter-university-system#77]
Activity for #54 
Monitor and close activity when it is completed.

**Comment by assiontetteh** [comment]
@SuDhAnShU-0611, since we have completed all User stories and the bigraphs, we need to move that activity to close that activity.

**Comment by Saarthak09** [comment]
@SuDhAnShU-0611 please close the prioritization task assigned to me after reviewing it.

**Comment by SuDhAnShU-0611** [comment]
@Saarthak09 I have closed the prioritization task after reviewing it

**Comment by SuDhAnShU-0611** [comment]
@assiontetteh Agreed, lets just review if everyone has completed their tasks and then we can move that activity to close that activity
