### ISSUE TITLE
Create Issues for Activities under Epic: "Prioritize user stories"

### ISSUE THREAD

**Issue by agvidit1** [assiontetteh/smarter-university-system#79]
Activity for Epic #49 

Create issues for activity for epic: "Prioritize user stories" and assign label activity

**Comment by Shanks0407** [comment]
Hi @Saarthak09 , I have created some issues under the epic #50 - Create user stories can you please verify them and let me know if i need to add or remove something from there.

**Comment by Saarthak09** [comment]
@Shanks0407 I have reviewed the issues you created, looks great no need to add or remove anything.
