### ISSUE TITLE
Implementing binary tree algorithm, to decide the priority - by Assion

### ISSUE THREAD

**Issue by Shanks0407** [assiontetteh/smarter-university-system#91]
Activity for Epic #52:
Each member decides the user story priority by using the binary tree algorithm. 
Hence this task is assigned to Assion to create his binary tree and decide priority using the tree.

**Comment by agvidit1** [comment]
@assiontetteh I believe we can discuss regarding priority tree created by you during the next meeting. Reserving some time for the same.

**Comment by agvidit1** [comment]
@assiontetteh Thanks for discussion, binary graph looks good now.
