### ISSUE TITLE
Implementing binary tree algorithm, to decide the priority - by Saarthak

### ISSUE THREAD

**Issue by Shanks0407** [assiontetteh/smarter-university-system#92]
Activity for Epic #52:
Each member decides the user story priority by using the binary tree algorithm. 
Hence this task is assigned to Saarthak to create his binary tree and decide priority using the tree.

**Comment by Saarthak09** [comment]
This task has been completed. Request all to kindly review.

**Comment by Shanks0407** [comment]
I have reviewed it and it looks good, all the priorities align with your binary tree. Great work ! @Saarthak09

**Comment by Saarthak09** [comment]
Thanks for reviewing it @Shanks0407
