### ISSUE TITLE
Creating binary trees in GraphViz- by Tetteh

### ISSUE THREAD

**Issue by assiontetteh** [assiontetteh/smarter-university-system#94]
Activity for Epic #52:
Visualizing the requirement prioritized using binary tree algorithm by using GraphViz
This Issue is created for Tetteh to complete and document his digraph.

**Comment by assiontetteh** [comment]
@Shanks0407 @agvidit1 @Saarthak09 I have created the Binary Tree as agreed.

**Comment by Shanks0407** [comment]
@assiontetteh the tree looks good please update the priorities sheet according to your tree too.

**Comment by Saarthak09** [comment]
@assiontetteh looks good.

**Comment by agvidit1** [comment]
@assiontetteh looks good. Good work in correct updation of priorities.
