### ISSUE TITLE
Creating binary trees in GraphViz - by Sudhanshu

### ISSUE THREAD

**Issue by assiontetteh** [assiontetteh/smarter-university-system#96]
Activity for Epic #52:
Visualizing the requirement prioritized using binary tree algorithm by using GraphViz
This Issue is created for Sudhanshu to complete and document his digraph.

**Comment by SuDhAnShU-0611** [comment]
The code for binary tree has been completed along with visualization.
The link to the code: https://docs.google.com/document/d/1BMCESI7vp-z1goPRvHmq-gmGbdhuhDwSP3Io0zQ7_HQ/edit

**Comment by SuDhAnShU-0611** [comment]
@agvidit1 Can you Check my graph as well? just to ensure that nothing is wrong

**Comment by assiontetteh** [comment]
@SuDhAnShU-0611 I have reviewed your binary tree as agreed. I think it look good; we will do a final review together for all Binary Search Tree before submission. Thank you.

**Comment by SuDhAnShU-0611** [comment]
@assiontetteh Thank you for reviewing it. And sure we will do a final review together before submission.

**Comment by agvidit1** [comment]
@SuDhAnShU-0611 Yes I have reviewed it, looks good. We can sit together to ensure priority ranking in excel matches with graph created.
