### ISSUE TITLE
Creating binary trees in GraphViz - by Saarthak

### ISSUE THREAD

**Issue by assiontetteh** [assiontetteh/smarter-university-system#97]
Activity for Epic #52:
Visualizing the requirement prioritized using binary tree algorithm by using GraphViz.
This Issue is created for Saarthak to complete and document his digraph.

**Comment by agvidit1** [comment]
@Saarthak09 There were issues that parents had placeholder child with names different than parent, i.e 10 node has child called 'L3'. Its good we have resolved such cases together.
