### ISSUE TITLE
Create API test inputs for parameters recipients and post_time

### ISSUE THREAD

**Issue by assiontetteh** [assiontetteh/smarter-university-system#98]
Activity for #51 API Testing for parameters recipients and post_time

**Comment by assiontetteh** [comment]
@agvidit1 @Saarthak09 @SuDhAnShU-0611 I have created the issue for Create API test input as discussed and will be working on it before our next meeting.

**Comment by assiontetteh** [comment]
@agvidit1 @Saarthak09 @SuDhAnShU-0611 I have created the Test Input for the API Testing.

**Comment by SuDhAnShU-0611** [comment]
@assiontetteh Thats great now we can move to the next part

**Comment by Saarthak09** [comment]
@assiontetteh looks great.

**Comment by agvidit1** [comment]
@assiontetteh Looks good. Thanks for the work.
