### ISSUE TITLE
Creating 2nd additional test cases that causes quizzes module to fail.

### ISSUE THREAD

**Issue by agvidit1** [assiontetteh/smarter-university-system#99]
Activity for Epic #53 

Adding the 2nd function to the already existing test_expose_failure_01() , The focus is on the quizzes module where the aim of writing the unit test is to cause the application to crash
Each program will exit prematurely.
No two test cases can cause a crash in the same line of code.
The crash induced for every one of the test cases must be at a different line of the program
Specifying the file and the line number where the program is crashing

**Comment by agvidit1** [comment]
2nd case identified and added. It can be seen in the PR raised.

**Comment by SuDhAnShU-0611** [comment]
Noted! Thank you for the work
